import { Section } from './types';


export const versions: Record<string, Section> = {
  background: {
    shortest: `Bay Area, Los Angeles, USC, Biomedical Engineering, USC Computer Science`,
    shorter: `I’ve lived in California my entire life, growing up in the Bay Area and then moving to Los Angeles for college and work after.  I went to USC for my undergrad and graduate degrees, studying Biomedical Engineering for my bachelors with a computer programming minor and computer science in grad school.`,
    longer: `I’ve lived in California my whole life, growing up in the Bay Area and spending the last 8 years in LA for school and work.  As an undergrad, tip-toed the path between doctor and engineer and studied biomedical engineering.  
              \n\nIn my coursework I got a big range of science/engineering spanning from electrical engineering, organic chemistry, physics, medical devices development, and biology (not to mention the Eastern European Crime Literature gen ed course I took!).  
              \n\nEventually I decided to opt out of premed and save an extra 7-10 years.  I knew I liked engineering and that I could find a fulfilling career in the field.  
              \n\n…and I didn’t want to take O Chem B.
              \n\nI also found that I enjoyed the programming I’d done in my engineering courses, so tacked on a computer programming minor to my degree (we call this foreshadowing).  I learned about object oriented programming, data structures/algorithms, and IoT devices in my courses.  
              \n\nMy new found interest in programming was tied with my broader growing interest in technology at large.  I found the medical devices course much more interesting than the bioengineering course I took.  I liked learning about electronics circuits in my EE courses more than electromagnetism in physics.  I had an idea of where to go next.
              `,
    longest: `I was born at a very young age. 
              \n\nI’ve lived in California my whole life and come from a very Californian family.  Both of my mom’s parents are immigrants, but my dad’s family goes back 6 generations in California these days.  I grew up in the San Jose area in the heart of Silicon Valley.  I remember driving past Netflix on the way to the batting cages back in my little league days back when they were still a DVD distribution company.  When I was applying to college, my parents thought I should do engineering because I liked puzzles and legos as a child.I ventured out of state(-ish) for college going all the way to Los Angeles to attend USC.  I straddled a high schooler’s indecision of wanting to be an engineer vs a doctor by studying Biomedical Engineering.  Eventually the engineer won out after surviving OChem A and deciding that OChem B was not worth it for the option to go to medical school.  Engineering was pulling more than medicine was.
              \n\nWhen I was 18, my mother bullied me into taking Comp Sci AP as a senior in high school.  I hated it.  Alas, I gave programming a second chance in college since it seemed helpful to my engineering classes.  You hate to admit it, but our mothers tend to be right.  I loved it the second time around and added a Computer Programming minor to my degree.  I took classes on top of my biomedical degree learning about data structures, algorithms, and IoT devices.  
              \n\nIn my biomedical engineering courses, I got a jack-of-all-trades, master of none education.  What do organic chemistry, physics, biology, tissue engineer, biomechanics, electrical engineering, statistics all have in common?  Maybe science? I’m not really sure. They were all adjacent courses, but didn’t build off each other to create much depth.  I graduated with a wide range of knowledge without a deep expertise in any one area.  
              \n\nDuring undergrad, I also got experience doing research with a lab that built devices to help children with movement disabilities, like cerebral palsy.  I got experience my first device experience here designing a research project that analyzed the coactivation patterns of forearm muscles from EGM signals with a Matlab script.
              \n\nI found I liked this device side of biomedical engineering better than the lab side, so that’s what I pursued after school.  I managed to find a job that was looking for a jack-of-all-trades at Abbott Labs’ Cardiac Rhythm Management division (think pacemakers).  Located in the hell-scorched land of Sylmar in San Fernando Valley, north of LA, I commuted up the 405 every day after graduating and move to West LA.`
  },
  career: {
    shortest: `Abbott Labs, Pacemakers, Product Development, Grad School, Computer Science, Abbott Labs, Firmware `,
    shorter: `I stayed put in LA after graduating, but jumped from university to Abbott Labs’s cardiac device division, where I got a job as systems engineer.  I worked for over 2 years there learning a lot about regulated product development processes and working on the design, development, and verification of Class II and III FDA regulated medical devices like pacemakers and cardiac monitors.  
              \n\nAfter one year on the job, I started a work + school program with USC studying computer science and was doing both full-time work and full-time grad school.  After over a year of doing both, I ended up deciding to leave work to focus on getting more technical at school. I went back to Abbott the following summer, to intern with their firmware team and help write the code on the actual pacemakers.
              `,
    longer: `I always enjoy working on things that are physical.  In college, I found that in my biomedical engineer degree that I enjoyed the large scale engineering side a lot more than the small scale bio-side.  This led me to opt into medical devices space over a more sciency space like bioengineering. 
              \n\nI landed a job at Abbott Labs pacemaker division in LA (well, technically the Valley) where I helped design medical devices and verify that they worked as specified. 
              \n\nAt Abbott, I was a systems engineer (think product development) and helped build FDA Class II and III medical devices like insertable cardiac monitors (reads your heartbeat for abnormalities), traditional pacemakers (box with chords that shock your heart to make it beat), and dual chamber leadless pacemakers (little boxes that goes inside your heart and shock it).
              \n\nAfter a year working I realized that I wanted to get more technical so I did an work/school program with USC to get a masters in Computer Science.  For the following year I was doing full-time school and full-time masters work and not sleeping a lot.  Eventually the gravitational pull of computer science won out and I ended up quitting my job to focus full time on school
              \n\nDoing solely grad school now, I was able to focus on my classwork and explore the CS field more.  During my summer break that year, I had a reunion with Abbott and spent the summer interning with the firmware team.  I got the chance to go from the high level design of the devices as a systems engineer to helping write the FW code on the actual pacemakers with the FW team that summer.`,
    longest: `As a systems engineer, I worked on tasks ranging from system design, requirement definition, device verification, and testing.  A good analogy for system engineering if you’re unfamiliar, is that they are the center of a wheel and facilitate the work of the other teams which are the spokes of the wheel.  The systems team defines the product, gives the work to subcomponent teams (electrical, firmware, software), they build the product according to the system team’s specifications, then give the result back to systems to verify it works properly and meets specifications.  Sound a little cumbersome?  Welcome to the world of regulated medical devices!
              \n\nWhile medical devices is an industry that evolves slowly and is generally a few generations of technology behind this was a great way to learn how to build in my opinion.  It is fairly counter to the popular tech ideology of building fast and breaking things, but this slow version of product development taught me what to look for and think about when building and defining a product and how to make sure it does what it’s suppose to do.  
              \n\nPerhaps not as exciting as moving fast, but fairly important when considering if the device messes up, someone could die.  
              \n\nAfter a year on the job, I decided I wanted to get more technical, so I applied to online graduate school at USC for computer science.  I found that the days at work that I enjoyed the most were days that I used my programming abilities and figured that to be a good sign to pursue that area further.  It also didn’t hurt that a CS degree would open future employment avenues outside of the medical device field.
              \n\nSomewhat masochistically, I did over a year of full-time school and work.   In late 2023, I decided I’d had enough and quit my job to just pursue school .  It’d been over two years on the job and I’d learned a lot but could feel myself starting to stagnate.  At the same time I was getting pulled more and more into the world of CS in school.  
              \n\nEinstein once said, “The more I learn, the more I realize how much I don’t know.”  One of the reasons that CS pulled me in was that it provided a promise to answers the questions I had of how things work in this world.  How is it that pressing a button on my keyboard can change a graphics screen in front of separate desktop?  How does a text message get sent over the internet to my friend in another state?
              \n\nGrad school taught me these things.  I took classes in operating systems, web technologies, search engines, software architecture, networking, and more.  It answered a lot of the questions I had before going to grad school, but now that I’ve learned a lot, I truly understand how much there is to know and how little I know in the grand scheme of things.
              \n\nA masters in computer science gave me a wide understanding of the field and CS truly is a science.   What may seem very technical on the outside ended up being a little bit of a lot of different fields.  A jack-of-all-trades, master-of-none.  I’d fallen for it again.  
              \n\nDuring my summer break in grad school, I worked an internship at Abbott again, as a firmware engineer. For those three months I helped the FW team doing R&T phase work on a new pacemaker platform. It was a great experience, but still equated to roughly another course’s worth of knowledge, not a mastery of anything.  
              \n\nSo at the end of 2024, I had a piece of paper saying I was a master and a bunch of well-rounded knowledge about computers and software.  I’d accomplished my goal and was definitely more technical with more hard skills than I had been 2.5 years prior, but I still haven’t shaken the title of jack-of-all-trades, master-of-none.  I’ve come to opinion that i don’t think that’s a bad thing.`  
  },
  personal: {
    shortest: `World travel/real-life hiatus, Giants baseball, NYT’s Games, bass guitar, learning languages, baking, music, writing.`,
    shorter: `I don’t think there’s a good way to do a personal section with a level of detail between Shortest/Longer.
              \n\nMy grandmother thinks I’m a delight.`,
    longer: `Writing this section feels like I’m filling out an eHarmony profile.
              \n\nHi 👋 My name is Jack!
              \n\nIn the mornings, I enjoy caffeinating ☕️and doing the NYT Mini, Wordle, and Connections (in that order).  
              \n\nIn the evening I fulfill my civic male duty and watch my hometown sports teams 🧢⚾️🏟️🏈🏀 (Giants baseball, Niners football, and Warriors basketball).  
              \n\nI also like cooking 👨‍🍳🌮🍽️ dinner with friends (and he cooks, he’s the whole package!).  And by cooking with friends, I mean, I cook and they just watch.
              \n\nBack when I lived in a house with a yard I got into woodwork 🪚🧰🪵🔨 for a bit.  (wow! he’s so capable! and rugged!)  
              \n\nI spent the first 7 months of the year doing some solo backpacking hitting 20 countries and 5 continents.  ✈️🌏⛰️🏝️
              \n\nI know how to program and sometimes do that for fun.  🤓💻
              \n\nI like trying to learn languages I’ll never be fluent in.  
              \n\nAt one point on my trip I was doing flashcards for 5 different languages.  I’ve got that number down to 2.5 now. 
              \n\nI love music, and listen to mostly indie and rock (he’s not like the other boys!).  I also play a handful of instruments fairly poorly (it’s the effort that counts).    🎸🥁🎹`,
    longest: `If you’ve read all the other Longest sections and you’re still willing to read another to get to me better, thanks for the interest.  If you want to save some time and not read this, reach out directly!
              \n\nAnyways. Here are some not work/school related things about me.
              \n\nAfter finishing my graduate program this past December, I fled the country.  I then spent the first 7 months of the 2025 backpacking around the world, eating street food, talking to strangers and sleeping in hostels across 20 countries and 5 continents.  
              \n\nOne of the coolest things I’ve done in my life.  I’d say this trip was more valuable to my education than all the GE courses I had to take during college.  I’d talk about it more, but I’ve already written about it. 
              \n\nI’m a big Bay Area sports fan (Giants/Warriors/49ers).  I stand by my take that sports is the equivalent of reality for TV for guys.  It’s my favorite no-thinking activity and it’s a great way to force my friends to hang out.
              \n\nI have a caffeine addiction (it’s good for us right??) that is the highlight of my morning.  My morning routine normally involves coffee, then do New York Times games (Mini => Wordle => Connections).  I’ve lost a step over the years, but I will brag for an eternity about the time I broke 10 seconds in the mini.
              \n\nI also have an obsession with trying to learn languages.  At one point traveling this year, I was doing flashcards for 5 different languages.  I admit this was too much and I’ve scaled it back to 3.   I don’t think I’ll ever be fluent, but I’ve learned enough Italian to make my hostel roommates from Milan laugh, enough German to order at a Biergarten, and enough Japanese to identify the sign for toilet.  I even built a piece of software to help me out with it.  
              \n\nMusic is a huge part of my life.  My dad doesn’t understand how I can focus, but I almost always have my headphones in while I do work.  My spotify reported that I listened to over 80k minutes of music last year (yes, I’m bragging online about this, I’m proud).  
              \n\nMy inner engineering urge understand how everything works lead me to try out guitar.  Similar to my experience with language, my ambition has tendencies to exceed the bounds of reality.  At one point I was trying to learn 4 different instruments.  I’ve also scaled it down to just bass guitar, and normal guitar, but I have a bookmark down to learn piano later in life.
              \n\nWhen I have free time I also like cooking with friends.  A lot of the time this involves me baking and my friends eating the sweets I make, but that’s fine by me.  We have a bit of a quid pro quo, where I have a sweet tooth but don’t want to eat a whole batch of cookies, so I trade baked goods for absolvement of entire cookie tray of guilt.
              \n\nOut of college, I lived in a house with a backyard.  I also lacked furniture in my room.  Combine the engineering brain with a surplus of new found free time now that I only working full-time now and not in engineering school anymore, lead to me build my own furniture.  You can check it out here.  I’ve built a bookshelf, an insanely heavy picnic bench, a couch table,  a spice rack, and a piano stool and have done a lot of Home Depot trips.  I also built a shoe rack out of old Ikea shelves that I found on the street.
              \n\nMy nerd activities on the side include programming connected devices (think arduinos).  Before my trip, I set up a VPN at my home with a raspberry pi (that I never used).  I’ve built alarm clocks with infrared sensors, and paper towel dispensers with radar sensors.  Sometimes I dabble in lighting fixtures. Computers are pretty cool.`,
  }
};
