import { BlogHeaderData } from '../../types/BlogHeaderData';

export const data: BlogHeaderData[] = [
  {
    "title": "Final Final - The Future",
    "id": 169857050,
    "link": "https://jtbelshe.substack.com/p/final-final-the-future",
    "subtitle": "A reflection on what this all means now that it's over",
    "image_local": "/images/the-great-escape/final-final-the-future-70e6e642f4.png",
    "name": "Jack T. Belshe",
    "reaction_count": 6,
    "comment_count": 3,
    "content_date": "Fri, 15 Aug 2025 11:03:25 GMT"
  },
  {
    "title": "Final Final - The Past",
    "id": 169931840,
    "link": "https://jtbelshe.substack.com/p/final-final-the-past",
    "subtitle": "Another reflection with a Lessons Learned and a By The Numbers",
    "image_local": "/images/the-great-escape/final-final-the-past-774f1a9272.jpeg",
    "name": "Jack T. Belshe",
    "reaction_count": 3,
    "comment_count": 1,
    "content_date": "Tue, 12 Aug 2025 11:02:47 GMT"
  },
  {
    "title": "Final Final - The Present",
    "id": 169928738,
    "link": "https://jtbelshe.substack.com/p/final-final-the-present",
    "subtitle": "A reflection of how I currently feel at the end of the rainbow",
    "image_local": "/images/the-great-escape/final-final-the-present-6a6711c4ad.jpeg",
    "name": "Jack T. Belshe",
    "reaction_count": 4,
    "comment_count": 4,
    "content_date": "Sat, 09 Aug 2025 14:49:03 GMT"
  },
  {
    "title": "Part 40: In Bruges",
    "id": 168017893,
    "link": "https://jtbelshe.substack.com/p/part-40-in-bruges",
    "subtitle": "I'm glad this is ending on such a divisible number",
    "image_local": "/images/the-great-escape/part-40-in-bruges-0c1aeef0fd.jpeg",
    "name": "Jack T. Belshe",
    "reaction_count": 2,
    "comment_count": 2,
    "content_date": "Wed, 06 Aug 2025 12:34:46 GMT"
  },
  {
    "title": "Part 39: Amster-damn It's Awesome Here",
    "id": 169399461,
    "link": "https://jtbelshe.substack.com/p/part-39-amsterdam-n-its-awesome-here",
    "subtitle": "I Am(sterdam) Enjoying Myself Here",
    "image_local": "/images/the-great-escape/part-39-amsterdamn-it-s-awesome-here-37bad19511.jpeg",
    "name": "Jack T. Belshe",
    "reaction_count": 1,
    "comment_count": 5,
    "content_date": "Thu, 31 Jul 2025 16:14:53 GMT"
  },
  {
    "title": "Part 38: Brat(islava) Summer",
    "id": 169121112,
    "link": "https://jtbelshe.substack.com/p/part-38-bratislava-summer",
    "subtitle": "Closing moments in Vienna and an in-depth review of Slovak food",
    "image_local": "/images/the-great-escape/part-38-brat-islava-summer-28f2b3b4d1.jpeg",
    "name": "Jack T. Belshe",
    "reaction_count": 0,
    "comment_count": 2,
    "content_date": "Mon, 28 Jul 2025 10:02:39 GMT"
  },
  {
    "title": "Part 37: Austrian Grandeur",
    "id": 168765026,
    "link": "https://jtbelshe.substack.com/p/part-37-austrian-grandeur",
    "subtitle": "A week exploring the question: Why is it so damn nice here?",
    "image_local": "/images/the-great-escape/part-37-austrian-grandeur-1e3ed2cd2b.jpeg",
    "name": "Jack T. Belshe",
    "reaction_count": 1,
    "comment_count": 2,
    "content_date": "Thu, 24 Jul 2025 13:04:10 GMT"
  },
  {
    "title": "Part 36: A More Traditional Germany",
    "id": 168574393,
    "link": "https://jtbelshe.substack.com/p/part-36-a-more-traditional-germany",
    "subtitle": "Bavaria is beautiful name for a baby girl",
    "image_local": "/images/the-great-escape/part-36-a-more-traditional-germany-6628024588.jpeg",
    "name": "Jack T. Belshe",
    "reaction_count": 0,
    "comment_count": 3,
    "content_date": "Sun, 20 Jul 2025 10:02:20 GMT"
  },
  {
    "title": "Part 35: A Second Chance For Berlin",
    "id": 168017812,
    "link": "https://jtbelshe.substack.com/p/part-35-a-second-chance-for-berlin",
    "subtitle": "Exploring the areas of Berlin, trying to find something",
    "image_local": "/images/the-great-escape/part-35-a-second-chance-for-berlin-6330b629d5.jpeg",
    "name": "Jack T. Belshe",
    "reaction_count": 3,
    "comment_count": 2,
    "content_date": "Wed, 16 Jul 2025 10:02:44 GMT"
  },
  {
    "title": "Part 34: Ich Bin Ein Berliner",
    "id": 167892587,
    "link": "https://jtbelshe.substack.com/p/part-34-ich-bin-ein-berliner",
    "subtitle": "The start of my stay in a confusing city with a deep and ongoing history",
    "image_local": "/images/the-great-escape/part-34-ich-bin-ein-berliner-01866c3c55.jpeg",
    "name": "Jack T. Belshe",
    "reaction_count": 2,
    "comment_count": 2,
    "content_date": "Fri, 11 Jul 2025 10:02:46 GMT"
  },
  {
    "title": "Part 33: The Danish Masterpiece ",
    "id": 167591239,
    "link": "https://jtbelshe.substack.com/p/part-33-the-danish-masterpiece",
    "subtitle": "Copenhagen? More Like Copen-hangin' out and having a good time 🤙",
    "image_local": "/images/the-great-escape/part-33-the-danish-masterpiece--f6f3c3ffe5.jpeg",
    "name": "Jack T. Belshe",
    "reaction_count": 5,
    "comment_count": 4,
    "content_date": "Mon, 07 Jul 2025 10:10:13 GMT"
  },
  {
    "title": "Part 32: Dublin Reunions",
    "id": 167064332,
    "link": "https://jtbelshe.substack.com/p/part-32-dublin-reunions",
    "subtitle": "I (kinda) crash family trips and weddings in the Nashville of Europe",
    "image_local": "/images/the-great-escape/part-32-dublin-reunions-60e6678902.jpeg",
    "name": "Jack T. Belshe",
    "reaction_count": 8,
    "comment_count": 4,
    "content_date": "Fri, 04 Jul 2025 10:02:10 GMT"
  },
  {
    "title": "Part 31: Everyone I Know Is In London",
    "id": 166666401,
    "link": "https://jtbelshe.substack.com/p/part-31-everyone-i-know-is-in-london",
    "subtitle": "I didn't choose the pub life, it chose me",
    "image_local": "/images/the-great-escape/part-31-everyone-i-know-is-in-london-bcc26334f7.jpeg",
    "name": "Jack T. Belshe",
    "reaction_count": 5,
    "comment_count": 3,
    "content_date": "Tue, 01 Jul 2025 06:17:45 GMT"
  },
  {
    "title": "Part 30: Touch Down in London Town",
    "id": 166306610,
    "link": "https://jtbelshe.substack.com/p/part-30-touch-down-in-london-town",
    "subtitle": "A familiar start to a new city",
    "image_local": "/images/the-great-escape/part-30-touch-down-in-london-town-bd1af04863.jpeg",
    "name": "Jack T. Belshe",
    "reaction_count": 4,
    "comment_count": 6,
    "content_date": "Fri, 20 Jun 2025 15:54:35 GMT"
  },
  {
    "title": "Part 29: An Edinburgh Breather",
    "id": 165774507,
    "link": "https://jtbelshe.substack.com/p/part-29-an-edinburgh-breather",
    "subtitle": "Call Edinburgh, Sabrina Carpenter, the way my debut be Short 'n Sweet (2024)",
    "image_local": "/images/the-great-escape/part-29-an-edinburgh-breather-3a50de7fd5.jpeg",
    "name": "Jack T. Belshe",
    "reaction_count": 2,
    "comment_count": 4,
    "content_date": "Sat, 14 Jun 2025 11:02:13 GMT"
  },
  {
    "title": "Part 28: Je ne parle pa Français",
    "id": 165537676,
    "link": "https://jtbelshe.substack.com/p/part-28-je-ne-parle-pa-francais",
    "subtitle": "Toursting as a local and the longest weekend yet",
    "image_local": "/images/the-great-escape/part-28-je-ne-parle-pa-français-eaee54145e.jpeg",
    "name": "Jack T. Belshe",
    "reaction_count": 2,
    "comment_count": 7,
    "content_date": "Wed, 11 Jun 2025 10:02:40 GMT"
  },
  {
    "title": "Part 27: Viva Paris ",
    "id": 165120735,
    "link": "https://jtbelshe.substack.com/p/part-27-viva-paris",
    "subtitle": "From Paris, with sore legs...",
    "image_local": "/images/the-great-escape/part-27-viva-paris--9b0106aa64.jpeg",
    "name": "Jack T. Belshe",
    "reaction_count": 3,
    "comment_count": 6,
    "content_date": "Thu, 05 Jun 2025 10:02:43 GMT"
  },
  {
    "title": "Part 26: 36 Hours in Geneva ",
    "id": 164955345,
    "link": "https://jtbelshe.substack.com/p/part-26-36-hours-in-geneva",
    "subtitle": "Does it bother anyone else having the 26 + 36 so close together in the title?",
    "image_local": "/images/the-great-escape/part-26-36-hours-in-geneva--59340b106b.jpeg",
    "name": "Jack T. Belshe",
    "reaction_count": 6,
    "comment_count": 2,
    "content_date": "Tue, 03 Jun 2025 10:06:17 GMT"
  },
  {
    "title": "Part 25: Italian B-Side Hits",
    "id": 164537994,
    "link": "https://jtbelshe.substack.com/p/part-25-italian-b-side-hits",
    "subtitle": "A northward migration through Florence and Milan",
    "image_local": "/images/the-great-escape/part-25-italian-bside-hits-4c630aeae4.jpeg",
    "name": "Jack T. Belshe",
    "reaction_count": 8,
    "comment_count": 4,
    "content_date": "Fri, 30 May 2025 10:04:17 GMT"
  },
  {
    "title": "Part 24: Roma Part-a Two-a",
    "id": 163907564,
    "link": "https://jtbelshe.substack.com/p/part-24-roma-part-a-two-a",
    "subtitle": "Twice the cappuccinos, twice the blogs",
    "image_local": "/images/the-great-escape/part-24-roma-parta-twoa-3419ada35d.jpeg",
    "name": "Jack T. Belshe",
    "reaction_count": 5,
    "comment_count": 2,
    "content_date": "Sat, 24 May 2025 10:02:05 GMT"
  },
  // {
  //   "title": "Final Final The Future",
  //   "id": 169857050,
  //   "link": "https://jtbelshe.substack.com/p/final-final-the-future",
  //   "subtitle": "A reflection on what this all means now that it's over",
  //   "image_local": "/images/the-great-escape/final-final-the-future-70e6e642f4.png",
  //   "name": "Jack T. Belshe",
  //   "reaction_count": 6,
  //   "comment_count": 3,
  //   "content_date": "Fri, 15 Aug 2025 11:03:25 GMT"
  // },
  // // {
  // //   "title": "Final Final - The Future",
  // //   "id": 169857050,
  // //   "link": "https://jtbelshe.substack.com/p/final-final-the-future",
  // //   "subtitle": "A reflection on what this all means now that it's over",
  // //   "image_local": "/images/the-great-escape/final-final-the-future-265aff3df1.png",
  // //   "name": "Jack T. Belshe",
  // //   "reaction_count": 6,
  // //   "comment_count": 3,
  // //   "content_date": "2025-08-15T11:03:25.531Z"
  // // },
  // {
  //   "title": "Final Final - The Past",
  //   "id": 169931840,
  //   "link": "https://jtbelshe.substack.com/p/final-final-the-past",
  //   "subtitle": "Another reflection with a Lessons Learned and a By The Numbers",
  //   "image_local": "/images/the-great-escape/final-final-the-past-3965d1104a.jpg",
  //   "name": "Jack T. Belshe",
  //   "reaction_count": 3,
  //   "comment_count": 1,
  //   "content_date": "2025-08-12T11:02:47.821Z"
  // },
  // {
  //   "title": "Final Final - The Present",
  //   "id": 169928738,
  //   "link": "https://jtbelshe.substack.com/p/final-final-the-present",
  //   "subtitle": "A reflection of how I currently feel at the end of the rainbow",
  //   "image_local": "/images/the-great-escape/final-final-the-present-d6950c73d7.jpg",
  //   "name": "Jack T. Belshe",
  //   "reaction_count": 4,
  //   "comment_count": 4,
  //   "content_date": "2025-08-09T14:49:03.757Z"
  // },
  // {
  //   "title": "Part 40: In Bruges",
  //   "id": 168017893,
  //   "link": "https://jtbelshe.substack.com/p/part-40-in-bruges",
  //   "subtitle": "I'm glad this is ending on such a divisible number",
  //   "image_local": "/images/the-great-escape/part-40-in-bruges-5f0c12128f.jpg",
  //   "name": "Jack T. Belshe",
  //   "reaction_count": 2,
  //   "comment_count": 2,
  //   "content_date": "2025-08-06T12:34:46.448Z"
  // },
  // {
  //   "title": "Part 39: Amsterdam-n It's Awesome Here",
  //   "id": 169399461,
  //   "link": "https://jtbelshe.substack.com/p/part-39-amsterdam-n-its-awesome-here",
  //   "subtitle": "I Am(sterdam) Having A Good Time",
  //   "image_local": "/images/the-great-escape/part-39-amsterdam-n-it-s-awesome-here-f40bde48ef.jpg",
  //   "name": "Jack T. Belshe",
  //   "reaction_count": 1,
  //   "comment_count": 5,
  //   "content_date": "2025-07-31T16:14:53.684Z"
  // },
  // {
  //   "title": "Part 38: Brat(islava) Summer",
  //   "id": 169121112,
  //   "link": "https://jtbelshe.substack.com/p/part-38-bratislava-summer",
  //   "subtitle": "Closing moments in Vienna and an in-depth review of Slovak food",
  //   "image_local": "/images/the-great-escape/part-38-brat-islava-summer-b6cd5ed2f2.jpg",
  //   "name": "Jack T. Belshe",
  //   "reaction_count": 0,
  //   "comment_count": 2,
  //   "content_date": "2025-07-28T10:02:39.340Z"
  // },
  // {
  //   "title": "Part 37: Austrian Grandeur",
  //   "id": 168765026,
  //   "link": "https://jtbelshe.substack.com/p/part-37-austrian-grandeur",
  //   "subtitle": "A week exploring the question: Why is it so damn nice here?",
  //   "image_local": "/images/the-great-escape/part-37-austrian-grandeur-cd4f5e005e.jpg",
  //   "name": "Jack T. Belshe",
  //   "reaction_count": 1,
  //   "comment_count": 2,
  //   "content_date": "2025-07-24T13:04:10.595Z"
  // },
  // {
  //   "title": "Part 36: A More Traditional Germany",
  //   "id": 168574393,
  //   "link": "https://jtbelshe.substack.com/p/part-36-a-more-traditional-germany",
  //   "subtitle": "Bavaria is beautiful name for a baby girl",
  //   "image_local": "/images/the-great-escape/part-36-a-more-traditional-germany-9c6b7a041f.jpg",
  //   "name": "Jack T. Belshe",
  //   "reaction_count": 0,
  //   "comment_count": 3,
  //   "content_date": "2025-07-20T10:02:20.526Z"
  // },
  // {
  //   "title": "Part 35: A Second Chance For Berlin",
  //   "id": 168017812,
  //   "link": "https://jtbelshe.substack.com/p/part-35-a-second-chance-for-berlin",
  //   "subtitle": "Exploring the areas of Berlin, trying to find something",
  //   "image_local": "/images/the-great-escape/part-35-a-second-chance-for-berlin-b6a4b3b40d.jpg",
  //   "name": "Jack T. Belshe",
  //   "reaction_count": 3,
  //   "comment_count": 2,
  //   "content_date": "2025-07-16T10:02:44.438Z"
  // },
  // {
  //   "title": "Part 34: Ich Bin Ein Berliner",
  //   "id": 167892587,
  //   "link": "https://jtbelshe.substack.com/p/part-34-ich-bin-ein-berliner",
  //   "subtitle": "The start of my stay in a confusing city with a deep and ongoing history",
  //   "image_local": "/images/the-great-escape/part-34-ich-bin-ein-berliner-2ba610af6e.jpg",
  //   "name": "Jack T. Belshe",
  //   "reaction_count": 2,
  //   "comment_count": 2,
  //   "content_date": "2025-07-11T10:02:46.890Z"
  // },
  // {
  //   "title": "Part 33: The Danish Masterpiece ",
  //   "id": 167591239,
  //   "link": "https://jtbelshe.substack.com/p/part-33-the-danish-masterpiece",
  //   "subtitle": "Copenhagen? More Like Copen-hangin' out and having a good time 🤙",
  //   "image_local": "/images/the-great-escape/part-33-the-danish-masterpiece-7a143e5f2b.jpg",
  //   "name": "Jack T. Belshe",
  //   "reaction_count": 5,
  //   "comment_count": 4,
  //   "content_date": "2025-07-07T10:10:13.064Z"
  // },
  // {
  //   "title": "Part 32: Dublin Reunions",
  //   "id": 167064332,
  //   "link": "https://jtbelshe.substack.com/p/part-32-dublin-reunions",
  //   "subtitle": "I (kinda) crash family trips and weddings in the Nashville of Europe",
  //   "image_local": "/images/the-great-escape/part-32-dublin-reunions-f3ff3ac0ca.jpg",
  //   "name": "Jack T. Belshe",
  //   "reaction_count": 8,
  //   "comment_count": 4,
  //   "content_date": "2025-07-04T10:02:10.516Z"
  // },
  // {
  //   "title": "Part 31: Everyone I Know Is In London",
  //   "id": 166666401,
  //   "link": "https://jtbelshe.substack.com/p/part-31-everyone-i-know-is-in-london",
  //   "subtitle": "I didn't choose the pub life, it chose me",
  //   "image_local": "/images/the-great-escape/part-31-everyone-i-know-is-in-london-28079f17ec.jpg",
  //   "name": "Jack T. Belshe",
  //   "reaction_count": 5,
  //   "comment_count": 3,
  //   "content_date": "2025-07-01T06:17:45.737Z"
  // },
  // {
  //   "title": "Part 30: Touch Down in London Town",
  //   "id": 166306610,
  //   "link": "https://jtbelshe.substack.com/p/part-30-touch-down-in-london-town",
  //   "subtitle": "A familiar start to a new city",
  //   "image_local": "/images/the-great-escape/part-30-touch-down-in-london-town-478f1cc3c0.jpg",
  //   "name": "Jack T. Belshe",
  //   "reaction_count": 4,
  //   "comment_count": 6,
  //   "content_date": "2025-06-20T15:54:35.182Z"
  // },
  // {
  //   "title": "Part 29: An Edinburgh Breather",
  //   "id": 165774507,
  //   "link": "https://jtbelshe.substack.com/p/part-29-an-edinburgh-breather",
  //   "subtitle": "Call Edinburgh, Sabrina Carpenter, the way my debut be Short 'n Sweet (2024)",
  //   "image_local": "/images/the-great-escape/part-29-an-edinburgh-breather-0cc9034391.jpg",
  //   "name": "Jack T. Belshe",
  //   "reaction_count": 2,
  //   "comment_count": 4,
  //   "content_date": "2025-06-14T11:02:13.901Z"
  // },
  // {
  //   "title": "Part 28: Je ne parle pa Français",
  //   "id": 165537676,
  //   "link": "https://jtbelshe.substack.com/p/part-28-je-ne-parle-pa-francais",
  //   "subtitle": "Toursting as a local and the longest weekend yet",
  //   "image_local": "/images/the-great-escape/part-28-je-ne-parle-pa-fran-ais-8169fab869.jpg",
  //   "name": "Jack T. Belshe",
  //   "reaction_count": 2,
  //   "comment_count": 7,
  //   "content_date": "2025-06-11T10:02:40.329Z"
  // },
  // {
  //   "title": "Part 27: Viva Paris ",
  //   "id": 165120735,
  //   "link": "https://jtbelshe.substack.com/p/part-27-viva-paris",
  //   "subtitle": "From Paris, with sore legs...",
  //   "image_local": "/images/the-great-escape/part-27-viva-paris-7405604ab0.jpg",
  //   "name": "Jack T. Belshe",
  //   "reaction_count": 3,
  //   "comment_count": 6,
  //   "content_date": "2025-06-05T10:02:43.929Z"
  // },
  // {
  //   "title": "Part 26: 36 Hours in Geneva ",
  //   "id": 164955345,
  //   "link": "https://jtbelshe.substack.com/p/part-26-36-hours-in-geneva",
  //   "subtitle": "Does it bother anyone else having the 26 + 36 so close together in the title?",
  //   "image_local": "/images/the-great-escape/part-26-36-hours-in-geneva-3d0b834809.jpg",
  //   "name": "Jack T. Belshe",
  //   "reaction_count": 6,
  //   "comment_count": 2,
  //   "content_date": "2025-06-03T10:06:17.683Z"
  // },
  // {
  //   "title": "Part 25: Italian B-Side Hits",
  //   "id": 164537994,
  //   "link": "https://jtbelshe.substack.com/p/part-25-italian-b-side-hits",
  //   "subtitle": "A northward migration through Florence and Milan",
  //   "image_local": "/images/the-great-escape/part-25-italian-b-side-hits-bd37c4d8ac.jpg",
  //   "name": "Jack T. Belshe",
  //   "reaction_count": 8,
  //   "comment_count": 4,
  //   "content_date": "2025-05-30T10:04:17.089Z"
  // },
  // {
  //   "title": "Part 24: Roma Part-a Two-a",
  //   "id": 163907564,
  //   "link": "https://jtbelshe.substack.com/p/part-24-roma-part-a-two-a",
  //   "subtitle": "Twice the cappuccinos, twice the blogs",
  //   "image_local": "/images/the-great-escape/part-24-roma-part-a-two-a-2072530074.jpg",
  //   "name": "Jack T. Belshe",
  //   "reaction_count": 5,
  //   "comment_count": 2,
  //   "content_date": "2025-05-24T10:02:05.312Z"
  // },
  {
    "title": "Part 23: Roman Holiday",
    "id": 163907384,
    "link": "https://jtbelshe.substack.com/p/part-23-roman-holiday",
    "subtitle": "Get in losers, we're going to Europe",
    "image_local": "/images/the-great-escape/part-23-roman-holiday-0d3e8eb294.jpg",
    "name": "Jack T. Belshe",
    "reaction_count": 6,
    "comment_count": 6,
    "content_date": "2025-05-20T10:00:36.703Z"
  },
  {
    "title": "Part 22: Australian Goodnight",
    "id": 161108769,
    "link": "https://jtbelshe.substack.com/p/part-22-australian-goodnight",
    "subtitle": "Finishing off Leg #1 down under in Sydney",
    "image_local": "/images/the-great-escape/part-22-australian-goodnight-dd74213479.jpg",
    "name": "Jack T. Belshe",
    "reaction_count": 4,
    "comment_count": 4,
    "content_date": "2025-04-15T11:02:37.077Z"
  },
  {
    "title": "Part 21: A NEW ZEAL(for travel)AND(nature!)",
    "id": 160043452,
    "link": "https://jtbelshe.substack.com/p/part-21-a-new-zealfor-natureandlife",
    "subtitle": "I'll admit this title was a tad forced",
    "image_local": "/images/the-great-escape/part-21-a-new-zeal-for-travel-and-nature-1378cc1c5c.jpg",
    "name": "Jack T. Belshe",
    "reaction_count": 3,
    "comment_count": 2,
    "content_date": "2025-04-07T10:02:51.463Z"
  },
  {
    "title": "Part 20: Belshé's in New Zealand ",
    "id": 160043328,
    "link": "https://jtbelshe.substack.com/p/part-20-belshes-in-new-zealand",
    "subtitle": "It's just like home, if home was in a different continent",
    "image_local": "/images/the-great-escape/part-20-belsh-s-in-new-zealand-045a41433f.jpg",
    "name": "Jack T. Belshe",
    "reaction_count": 7,
    "comment_count": 4,
    "content_date": "2025-04-03T08:23:49.014Z"
  },
  {
    "title": "Part 19: The Sweatiest Man in Singapore",
    "id": 159532634,
    "link": "https://jtbelshe.substack.com/p/part-19-the-sweatiest-man-in-singapore",
    "subtitle": "Steps, Bites, and Pit Stains in the World's Nicest City",
    "image_local": "/images/the-great-escape/part-19-the-sweatiest-man-in-singapore-0b5976cd8f.jpg",
    "name": "Jack T. Belshe",
    "reaction_count": 4,
    "comment_count": 2,
    "content_date": "2025-03-25T08:27:23.368Z"
  },
  {
    "title": "Part 18: A Full Week of Bangkok",
    "id": 159320034,
    "link": "https://jtbelshe.substack.com/p/part-18-a-full-week-of-bangkok",
    "subtitle": "Bang!(*Mike Breen voice*)-kok",
    "image_local": "/images/the-great-escape/part-18-a-full-week-of-bangkok-18818dbec5.jpg",
    "name": "Jack T. Belshe",
    "reaction_count": 5,
    "comment_count": 4,
    "content_date": "2025-03-20T12:31:32.341Z"
  },
  {
    "title": "Part 17: Good Evening Vietnam!",
    "id": 158975227,
    "link": "https://jtbelshe.substack.com/p/part-17-good-evening-vietnam",
    "subtitle": "The sunsets in Saigon in our final Vietnam chapter",
    "image_local": "/images/the-great-escape/part-17-good-evening-vietnam-af04bcccca.jpg",
    "name": "Jack T. Belshe",
    "reaction_count": 7,
    "comment_count": 4,
    "content_date": "2025-03-15T09:08:31.761Z"
  },
  {
    "title": "Part 16: Hoi An Aloha",
    "id": 158287329,
    "link": "https://jtbelshe.substack.com/p/part-16-hoi-an-aloha",
    "subtitle": "New favorite spot alert ‼️",
    "image_local": "/images/the-great-escape/part-16-hoi-an-aloha-0a071279c7.jpg",
    "name": "Jack T. Belshe",
    "reaction_count": 8,
    "comment_count": 3,
    "content_date": "2025-03-09T15:05:49.917Z"
  },
  {
    "title": "Part 15: A Not So Ancient Capital",
    "id": 158093785,
    "link": "https://jtbelshe.substack.com/p/part-15-a-not-so-ancient-capital",
    "subtitle": "Journeying down the sliver that is Vietnam to its former capital Hue",
    "image_local": "/images/the-great-escape/part-15-a-not-so-ancient-capital-d179ce91d4.jpg",
    "name": "Jack T. Belshe",
    "reaction_count": 3,
    "comment_count": 4,
    "content_date": "2025-03-04T12:08:34.668Z"
  },
  {
    "title": "Part 14: Hanoi Slowdown",
    "id": 157733350,
    "link": "https://jtbelshe.substack.com/p/part-14-hanoi-slowdown",
    "subtitle": "We've hit our first little hiccup of the trip",
    "image_local": "/images/the-great-escape/part-14-hanoi-slowdown-f8803531c4.jpg",
    "name": "Jack T. Belshe",
    "reaction_count": 4,
    "comment_count": 3,
    "content_date": "2025-03-01T13:36:37.982Z"
  },
  {
    "title": "Part 13: The Hanoi Two-Step",
    "id": 157615775,
    "link": "https://jtbelshe.substack.com/p/part-13-the-hanoi-two-step",
    "subtitle": "Surviving these Vietnam Streets",
    "image_local": "/images/the-great-escape/part-13-the-hanoi-two-step-67f221bf0f.jpg",
    "name": "Jack T. Belshe",
    "reaction_count": 7,
    "comment_count": 9,
    "content_date": "2025-02-24T11:00:36.885Z"
  },
  {
    "title": "Part 12: Mo' Ho' Ko'",
    "id": 157187502,
    "link": "https://jtbelshe.substack.com/p/part-12-mo-ho-ko",
    "subtitle": "Second of my Hong Kong Stint",
    "image_local": "/images/the-great-escape/part-12-mo-ho-ko-9fca14868c.jpg",
    "name": "Jack T. Belshe",
    "reaction_count": 5,
    "comment_count": 6,
    "content_date": "2025-02-18T14:16:00.223Z"
  },
  {
    "title": "Part 11: Enter Hong Kong ",
    "id": 157128162,
    "link": "https://jtbelshe.substack.com/p/part-11-enter-hong-kong",
    "subtitle": "New city, new weather, same blog",
    "image_local": "/images/the-great-escape/part-11-enter-hong-kong-a3137f77a4.jpg",
    "name": "Jack T. Belshe",
    "reaction_count": 4,
    "comment_count": 8,
    "content_date": "2025-02-15T14:00:29.400Z"
  },
  {
    "title": "Part 10: Seoul-y S**t It's Cold",
    "id": 156838434,
    "link": "https://jtbelshe.substack.com/p/part-10-seoul-y-st-its-cold",
    "subtitle": "Please forgive my pun",
    "image_local": "/images/the-great-escape/part-10-seoul-y-s-t-it-s-cold-8c14e8ce21.jpg",
    "name": "Jack T. Belshe",
    "reaction_count": 4,
    "comment_count": 7,
    "content_date": "2025-02-12T13:14:54.154Z"
  },
  {
    "title": "Part 9: Tokyo Relapse",
    "id": 156152027,
    "link": "https://jtbelshe.substack.com/p/part-9-tokyo-relapse",
    "subtitle": "One last ride: Tokyo with some old friends",
    "image_local": "/images/the-great-escape/part-9-tokyo-relapse-ff6c6381af.jpg",
    "name": "Jack T. Belshe",
    "reaction_count": 4,
    "comment_count": 5,
    "content_date": "2025-02-06T12:03:44.026Z"
  },
  {
    "title": "Part 8: More Side Quests",
    "id": 156151512,
    "link": "https://jtbelshe.substack.com/p/part-8-more-side-quests",
    "subtitle": "Japanese, Beppu continued, and Kamakura",
    "image_local": "/images/the-great-escape/part-8-more-side-quests-0d009d0b7e.jpg",
    "name": "Jack T. Belshe",
    "reaction_count": 4,
    "comment_count": 4,
    "content_date": "2025-02-03T12:02:56.214Z"
  },
  {
    "title": "Part 7: Side Quests ",
    "id": 155984973,
    "link": "https://jtbelshe.substack.com/p/part-7-side-quests",
    "subtitle": "Hiroshima, Fukuoka, and Beppu ",
    "image_local": "/images/the-great-escape/part-7-side-quests-8fec94211a.jpg",
    "name": "Jack T. Belshe",
    "reaction_count": 5,
    "comment_count": 2,
    "content_date": "2025-01-31T12:08:55.994Z"
  },
  {
    "title": "Part 6: Anjin in Osaka ",
    "id": 155984522,
    "link": "https://jtbelshe.substack.com/p/part-6-anjin-in-osaka",
    "subtitle": "Eating, walking, talking, the usual up next",
    "image_local": "/images/the-great-escape/part-6-anjin-in-osaka-52d35b8fcc.jpg",
    "name": "Jack T. Belshe",
    "reaction_count": 5,
    "comment_count": 3,
    "content_date": "2025-01-29T12:59:40.421Z"
  },
  {
    "title": "Part 5: Tokyo Drift (to Kyoto)",
    "id": 155520229,
    "link": "https://jtbelshe.substack.com/p/part-5-tokyo-drift-to-kyoto",
    "subtitle": "Kyoto: Trains, Shrines, and Karaoke",
    "image_local": "/images/the-great-escape/part-5-tokyo-drift-to-kyoto-79228af118.jpg",
    "name": "Jack T. Belshe",
    "reaction_count": 3,
    "comment_count": 1,
    "content_date": "2025-01-26T13:24:40.591Z"
  },
  {
    "title": "Part 4.5: The Tsukiji Market Special",
    "id": 155520401,
    "link": "https://jtbelshe.substack.com/p/part-45-the-tsukiji-market-special",
    "subtitle": "A Deeper Dive Into My New Favorite Tourist Trap in Tokyo",
    "image_local": "/images/the-great-escape/part-4-5-the-tsukiji-market-special-17c855ebb1.jpg",
    "name": "Jack T. Belshe",
    "reaction_count": 8,
    "comment_count": 5,
    "content_date": "2025-01-24T11:50:31.917Z"
  },
  {
    "title": "Part 4: More Tokyo Steps and Bites",
    "id": 155519494,
    "link": "https://jtbelshe.substack.com/p/part-4-more-tokyo-steps-and-bites",
    "subtitle": "The end of the first beginning of the journey",
    "image_local": "/images/the-great-escape/part-4-more-tokyo-steps-and-bites-4517dc1ddc.jpg",
    "name": "Jack T. Belshe",
    "reaction_count": 6,
    "comment_count": 8,
    "content_date": "2025-01-23T14:02:30.802Z"
  },
  {
    "title": "Part 3: The Tokyo Blogs Shall Continue Until Behavior Improves",
    "id": 155200123,
    "link": "https://jtbelshe.substack.com/p/part-3-the-tokyo-blogs-shall-continue",
    "subtitle": "",
    "image_local": "/images/the-great-escape/part-3-the-tokyo-blogs-shall-continue-until-behavior-improve-99916d0ec3.jpg",
    "name": "Jack T. Belshe",
    "reaction_count": 8,
    "comment_count": 1,
    "content_date": "2025-01-20T14:03:39.387Z"
  },
  {
    "title": "Part 2: A Shinjuku Weekend",
    "id": 155064669,
    "link": "https://jtbelshe.substack.com/p/part-2-a-shinjuku-weekend",
    "subtitle": "Are we hitting our stride?",
    "image_local": "/images/the-great-escape/part-2-a-shinjuku-weekend-e433ed231c.jpg",
    "name": "Jack T. Belshe",
    "reaction_count": 8,
    "comment_count": 3,
    "content_date": "2025-01-18T13:20:23.381Z"
  },
  {
    "title": "Part 1: Intro to Japan",
    "id": 154880099,
    "link": "https://jtbelshe.substack.com/p/part-1-intro-to-japan",
    "subtitle": "Recap of the first few days in Tokyo",
    "image_local": "/images/the-great-escape/part-1-intro-to-japan-0053084a84.jpg",
    "name": "Jack T. Belshe",
    "reaction_count": 9,
    "comment_count": 2,
    "content_date": "2025-01-15T13:28:44.771Z"
  },
  {
    "title": "All Aboard",
    "id": 154515363,
    "link": "https://jtbelshe.substack.com/p/all-aboard",
    "subtitle": "Quick summary of my not so quick trip ",
    "image_local": "/images/the-great-escape/all-aboard-80ac4bc64d.jpg",
    "name": "Jack T. Belshe",
    "reaction_count": 10,
    "comment_count": 4,
    "content_date": "2025-01-10T07:54:54.937Z"
  },
]